### PR TITLE
Upgrade to bluebird 3

### PR DESCRIPTION
**Pull request by apechimp**

### CODE REVIEW

**Comment by apechimp** [comment]
CR @lanetix/engineers

**Comment by scarney81** [comment]
Dat failed build :sob:

**Comment by scarney81** [comment]
:sheep::sheep::sheep::sheep:
:sheep:LGTM:sheep:
:sheep::sheep::sheep::sheep:

**Comment by apechimp** [comment]
weird. Not sure why it's failing. It's failing to `DROP` the table it uses for testing in circle. It works fine locally :confused:.

**Pull request merged**
